In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [ ]:
data = pd.read_csv("data.csv");
data.head()

,Model,Year,Price,Transmission,Mileage,FuelType,Tax,MPG,EngineSize
0,Focus,2020,41477,Semi-Auto,51916.0,Diesel,237,73.7,3.3
1,EcoSport,2021,39996,Semi-Auto,29760.0,Diesel,199,59.2,1.1
2,Focus,2025,17317,Automatic,76684.0,Electric,0,76.9,0.0
3,Fiesta,2025,8973,Manual,47955.0,Diesel,190,73.0,1.1
4,Kuga,2022,23170,Automatic,38762.0,Petrol,202,83.3,2.8

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Model         500 non-null    object
 1   Year          500 non-null    int64
 2   Price         500 non-null    int64
 3   Transmission  475 non-null    object
 4   Mileage       475 non-null    float64
 5   FuelType      500 non-null    object
 6   Tax           500 non-null    int64
 7   MPG           475 non-null    float64
 8   EngineSize    475 non-null    float64
dtypes: float64(3), int64(3), object(3)
memory usage: 35.3+ KB

In [ ]:
data.isnull().sum()

Model            0
Year             0
Price            0
Transmission    25
Mileage         25
FuelType         0
Tax              0
MPG             25
EngineSize      25
dtype: int64

In [ ]:
data.duplicated().sum()

np.int64(13)

In [ ]:
data.shape

(500, 9)

In [ ]:
data.drop_duplicates(inplace=True)
data.shape

(487, 9)

In [ ]:
data.isnull().sum()

Model            0
Year             0
Price            0
Transmission    25
Mileage         25
FuelType         0
Tax              0
MPG             25
EngineSize      25
dtype: int64

In [ ]:
data['Mileage'].fillna(data['Mileage'].median(), inplace = True)

In [ ]:
col = data['EngineSize'].fillna(data['EngineSize'].median())
data['EngineSize'] = col
data['MPG'].fillna(data['MPG'].median(), inplace = True)

In [ ]:
trans = data['Transmission'].fillna(data['Transmission'].mode()[0])
data['Transmission'] = trans

In [ ]:
data.isnull().sum()

Model           0
Year            0
Price           0
Transmission    0
Mileage         0
FuelType        0
Tax             0
MPG             0
EngineSize      0
dtype: int64

In [ ]:
le = LabelEncoder()
data['Transmission'] = le.fit_transform(data['Transmission'])

data.head()

,Model,Year,Price,Transmission,Mileage,FuelType,Tax,MPG,EngineSize
0,Focus,2020,41477,2,51916.0,Diesel,237,73.7,3.3
1,EcoSport,2021,39996,2,29760.0,Diesel,199,59.2,1.1
2,Focus,2025,17317,0,76684.0,Electric,0,76.9,0.0
3,Fiesta,2025,8973,1,47955.0,Diesel,190,73.0,1.1
4,Kuga,2022,23170,0,38762.0,Petrol,202,83.3,2.8

In [ ]:
data['FuelType'] = le.fit_transform(data['FuelType'])
data['Model'] = le.fit_transform(data['Model'])
data.head()

   Model  Year  Price  Transmission  Mileage  FuelType  Tax   MPG  EngineSize
0      2  2020  41477             2  51916.0         0  237  73.7         3.3
1      0  2021  39996             2  29760.0         0  199  59.2         1.1
2      2  2025  17317             0  76684.0         1    0  76.9         0.0
3      1  2025   8973             1  47955.0         0  190  73.0         1.1
4      3  2022  23170             0  38762.0         3  202  83.3         2.8

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 487 entries, 0 to 499
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Model         487 non-null    int64
 1   Year          487 non-null    int64
 2   Price         487 non-null    int64
 3   Transmission  487 non-null    int64
 4   Mileage       487 non-null    float64
 5   FuelType      487 non-null    int64
 6   Tax           487 non-null    int64
 7   MPG           487 non-null    float64
 8   EngineSize    487 non-null    float64
dtypes: float64(3), int64(6)
memory usage: 38.0 KB

In [ ]:
X = data.drop("Price", axis=1)
Y = data['Price']

In [ ]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
X_train, X_test , y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 42)

model = GaussianNB()

model.fit(X_train, y_train)
y_pred = model.predict(X_test)
acc = accuracy_score(y_pred, y_test)
print(acc * 100)

1.0204081632653061

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

print(f"Mean Absolute Error (MAE): {mae}")
print(f"Mean Squared Error (MSE): {mse}")
print(f"Root Mean Squared Error (RMSE): {rmse}")

Mean Absolute Error (MAE): 15515.34693877551
Mean Squared Error (MSE): 355475416.0
Root Mean Squared Error (RMSE): 18854.05569101778

The model's performance should be evaluated using regression-specific metrics like MAE, MSE, or RMSE since the 'Price' variable is continuous. The values above provide a better understanding of how well the model predicts the 'Price'.